<a href="https://colab.research.google.com/github/mariyashk/numpy/blob/main/miniproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🎯 Objective:
You are working with student marks data and need to prepare and organize it using NumPy arrays.Your goal is to create, modify, and analyze the data efficiently without using any external libraries.

🧠 Project Description:
A school has recorded the marks of several students in different subjects.You are required to design a NumPy-based solution to store, manage, and process this data.Your tasks involve creating arrays, changing their shapes, combining data, performing modifications, and analyzing patterns — all using NumPy.

📋 Project Tasks:
1.Data Creation:**Create suitable arrays to represent students, subjects, and their marks.

2.Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.

3.Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.

4.Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.

5.Data Modification:**Apply operations to update marks, remove data, or identify unique information.

6.Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.

7.Copy and View Behavior:**Show the difference between creating a full copy of an array and creating a view of the same data.

In [1]:
import numpy as np

# 1. DATA CREATION

students = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eva'])
subjects = np.array(['Math', 'Science', 'English', 'History'])


marks = np.array([
    [85, 90, 78, 92],
    [88, 76, 85, 80],
    [90, 88, 82, 95],
    [70, 65, 75, 60],
    [95, 92, 88, 96]
])

print("🎓 Students:", students)
print("📘 Subjects:", subjects)
print("📊 Marks:\n", marks)

# 2. DATA EXPLORATION

print("\n🔍 Array Properties:")
print("Dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Size:", marks.size)
print("Data Type:", marks.dtype)
print("Item Size:", marks.itemsize, "bytes")

# 3. DATA TRANSFORMATION

flat_marks = marks.flatten()
print("\nFlattened Marks:", flat_marks)

reshaped_marks = marks.reshape(4, 5)
print("\nReshaped Marks (4x5):\n", reshaped_marks)

#4. DATA COMBINATION

new_student = np.array([[82, 79, 88, 90]])
marks = np.vstack([marks, new_student])
students = np.append(students, 'Frank')

print("\nAfter adding a new student:")
print("Students:", students)
print("Marks:\n", marks)

new_subject_marks = np.array([[89], [85], [92], [70], [98], [91]])
marks = np.hstack([marks, new_subject_marks])
subjects = np.append(subjects, 'Computer')

print("\nAfter adding a new subject:")
print("Subjects:", subjects)
print("Marks:\n", marks)

#5. DATA MODIFICATION

marks[:, 0] += 5
print("\nUpdated Marks after +5 in Math:\n", marks)

marks = np.delete(marks, 2, axis=0)
students = np.delete(students, 2)
print("\nAfter removing Charlie:")
print("Students:", students)
print("Marks:\n", marks)
unique_marks = np.unique(marks)
print("\nUnique Marks:", unique_marks)

#6. DATA TYPE HANDLING
marks_float = marks.astype(float)
print("\nMarks (Float Type):\n", marks_float)

avg_int = marks.sum(axis=1) // marks.shape[1]
avg_float = marks_float.sum(axis=1) / marks_float.shape[1]
print("\nAverage (Integer Division):", avg_int)
print("Average (Float Division):", avg_float)

#7. COPY vs VIEW BEHAVIOR

marks_view = marks.view()
marks_copy = marks.copy()
marks_view[0, 0] = 100
marks_copy[1, 1] = 0

print("\nOriginal Marks after modifying VIEW:\n", marks)
print("View Marks:\n", marks_view)
print("Copy Marks (Independent):\n", marks_copy)


🎓 Students: ['Alice' 'Bob' 'Charlie' 'David' 'Eva']
📘 Subjects: ['Math' 'Science' 'English' 'History']
📊 Marks:
 [[85 90 78 92]
 [88 76 85 80]
 [90 88 82 95]
 [70 65 75 60]
 [95 92 88 96]]

🔍 Array Properties:
Dimensions: 2
Shape: (5, 4)
Size: 20
Data Type: int64
Item Size: 8 bytes

Flattened Marks: [85 90 78 92 88 76 85 80 90 88 82 95 70 65 75 60 95 92 88 96]

Reshaped Marks (4x5):
 [[85 90 78 92 88]
 [76 85 80 90 88]
 [82 95 70 65 75]
 [60 95 92 88 96]]

After adding a new student:
Students: ['Alice' 'Bob' 'Charlie' 'David' 'Eva' 'Frank']
Marks:
 [[85 90 78 92]
 [88 76 85 80]
 [90 88 82 95]
 [70 65 75 60]
 [95 92 88 96]
 [82 79 88 90]]

After adding a new subject:
Subjects: ['Math' 'Science' 'English' 'History' 'Computer']
Marks:
 [[85 90 78 92 89]
 [88 76 85 80 85]
 [90 88 82 95 92]
 [70 65 75 60 70]
 [95 92 88 96 98]
 [82 79 88 90 91]]

Updated Marks after +5 in Math:
 [[ 90  90  78  92  89]
 [ 93  76  85  80  85]
 [ 95  88  82  95  92]
 [ 75  65  75  60  70]
 [100  92  88  96  98]